
;; UART 16C550 SERIAL Addresses

UART0:          .EQU    $10           ; DATA IN/OUT
UART1:          .EQU    $11           ; CHECK RX
UART2:          .EQU    $12           ; INTERRUPTS
UART3:          .EQU    $13           ; LINE CONTROL
UART4:          .EQU    $14           ; MODEM CONTROL
UART5:          .EQU    $15           ; LINE STATUS
UART6:          .EQU    $16           ; MODEM STATUS
UART7:          .EQU    $17           ; SCRATCH REG.

